#' Synthetic mosque orientation datasets
#'
#' A named list of ten small tibbles covering archetypal patterns that
#' `qiblalab` methods should detect or reject (design doc §19). Each element
#' is a self-contained dataset suitable for package examples and unit tests
#' that do not require network access.
#'
#' All tibbles share the core columns `mosque_id`, `latitude`, `longitude`,
#' `year_ce_min`, `year_ce_max`, and `azimuth`, plus scenario-specific columns.
#'
#' @format A named list with ten elements:
#' \describe{
#'   \item{`mecca_tradition`}{40 mosques across the Near East all oriented
#'     toward Mecca with 5-degree Gaussian noise. Demonstrates clear single-
#'     destination signal.}
#'   \item{`two_traditions`}{40 mosques split equally between a Mecca-pointing
#'     and a Petra-pointing tradition. Has a `tradition` column.}
#'   \item{`chronological`}{40 mosques: early mosques (pre-650 CE) oriented
#'     toward Petra, later mosques oriented toward Mecca. Demonstrates a
#'     temporal transition.}
#'   \item{`intermediate`}{60 mosques in three factions: one toward Mecca, one
#'     toward Petra, one toward the circular midpoint. Has a `faction` column.}
#'   \item{`cardinal`}{30 mosques: half oriented due south (180 deg), half
#'     following Mecca. Has an `orientation` column.}
#'   \item{`random_orientations`}{40 mosques with uniform random azimuths.
#'     The null model: no coherent directional tradition.}
#'   \item{`geographic_cluster`}{40 mosques in two geographic regions (Levant
#'     and Persia), both pointing toward Mecca. The apparent directional
#'     difference is caused by geography, not tradition. Has a `region` column.}
#'   \item{`over_clustered`}{40 mosques in a single tight directional cluster.
#'     Demonstrates that k > 1 produces spuriously high cluster purity.}
#'   \item{`uncertain_dates`}{30 mosques with wide date ranges (60-120 yr)
#'     spanning the c. 650 CE Petra-to-Mecca transition. Half were oriented to
#'     Petra, half to Mecca, but dates alone cannot separate them.}
#'   \item{`rebuilt_mosques`}{30 mosques: 15 originals pointing to Petra
#'     (rebuilt = FALSE), 15 later rebuilds pointing to Mecca
#'     (rebuilt = TRUE). Demonstrates the effect of including rebuilt mosques.}
#' }
#'
#' @source Generated by `data-raw/synthetic.R` with `set.seed(20240101)`.
#' @seealso [gibson_qibla], [destinations]
"qibla_scenarios"
